version: '3.8'

services:
  bot_image:
    image: registry.local:5000/bot_image:latest
    container_name: bot_image
    environment:
      - TOKEN=${TOKEN}
      - RM_HOST=${RM_HOST}
      - RM_PORT=${RM_PORT}
      - RM_USER=${RM_USER}
      - RM_PASSWORD=${RM_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT_SSH=${DB_PORT_SSH}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
    depends_on:
      - db_image
    networks:
      - my_network

  db_image:
    image: registry.local:5000/db_image:latest
    container_name: db_image
    environment:
      - DB_DATABASE=${DB_DATABASE}
      - DB_REPL_USER=${DB_REPL_USER}
      - DB_REPL_PASSWORD=${DB_REPL_PASSWORD}
    ports:
      - "5432:5432"
      - "22:22"
    networks:
      - my_network

  db_repl_image:
    image: registry.local:5000/db_repl_image:latest
    container_name: db_repl_image
    environment:
      - DB_DATABASE=${DB_DATABASE}
      - DB_REPL_USER=${DB_REPL_USER}
      - DP_REPL_PASSWORD=${DB_REPL_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_REPL_HOST=${DB_REPL_HOST}
      - DB_REPL_PORT=${DB_REPL_PORT}
    depends_on:
      - db_image
    ports:
      - "5433:5432"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge