CREATE TABLE emails (id SERIAL PRIMARY KEY, email VARCHAR(255) NOT NULL);
CREATE TABLE phone_numbers (id SERIAL PRIMARY KEY, phone_number VARCHAR(30) NOT NULL);
CREATE USER repl_user REPLICATION LOGIN ENCRYPTED PASSWORD 'kali';