CREATE TABLE emails (id SERIAL PRIMARY KEY, email VARCHAR(255) NOT NULL);
CREATE TABLE phone_numbers (id SERIAL PRIMARY KEY, phone_number VARCHAR(30) NOT NULL);
CREATE USER replaceREPLUSER REPLICATION LOGIN ENCRYPTED PASSWORD 'replaceREPLPASSWORD';

INSERT INTO phone_numbers (phone_number) VALUES ('88005553535');
INSERT INTO emails (email) VALUES ('example@test.try');
